"""
CIO Report Model

Represents the final investment report generated by
CIOEngine.

STOCK-CIO
"""

from __future__ import annotations

from dataclasses import dataclass

from src.models.decision import Decision


@dataclass(slots=True, frozen=True)
class CIOReport:
    """
    Final CIO investment report.

    Attributes
    ----------
    decision : Decision
        Final investment decision.

    portfolio_summary : str
        Portfolio status summary.

    recommended_action : str
        Recommended investment action.

    investment_comment : str
        Final CIO investment comment.
    """

    decision: Decision

    portfolio_summary: str

    recommended_action: str

    investment_comment: str