"""
Decision Model

Represents the final investment decision generated by
DecisionEngine.

STOCK-CIO
"""

from __future__ import annotations

from dataclasses import dataclass

from src.constants.decision_type import DecisionType


@dataclass(slots=True, frozen=True)
class Decision:
    """
    Final investment decision.

    Attributes
    ----------
    decision : DecisionType
        Final investment decision.

    confidence : float
        Confidence score (0.0 ~ 1.0).

    summary : str
        Summary of the decision.

    reason : str
        Detailed reason for the decision.
    """

    decision: DecisionType

    confidence: float

    summary: str

    reason: str